### ISSUE TITLE
UsageForm list of construals should be alphabetized

### ISSUE THREAD

**Issue by nschneid** [nert-gu/Xposition#10]

**Comment by ablodge** [comment]
Not sure where this list is generated
Relevent files: `wiki/plugins/metadata/forms.py`?

**Comment by nschneid** [comment]
It's automatically generated by a `UsageForm` instance: https://github.com/nert-gu/Xposition/blob/master/wiki/plugins/metadata/forms.py#L412

`UsageForm` inherits from `ModelForm`.

https://stackoverflow.com/a/42812014 claims that you can specify an `ordering` within the model, which I guess would be `Construal`.

**Comment by ablodge** [comment]
tried the following:
`class Construal(SimpleMetadata):
    ...
    class Meta:
        verbose_name = _('construal')
        unique_together = ('role', 'function')
        ordering = ['role', 'function']
`
I'm not sure why it doesn't work.

**Comment by nschneid** [comment]
The role of the construal is itself a `Supersense` object. I bet it defaults to sorting by the object ID, which reflects the order of creation. So maybe under the `Supersense` model also add an `ordering` by its name?

**Comment by ablodge** [comment]
I ended up doing this, and got it to work!
```
class Metadata()
        ...
        class Meta():
              verbose_name = _('metadata')
              ordering = ['current_revision__metadatarevision__name']
```
