### ISSUE TITLE
Special sections from English guidelines

### ISSUE THREAD

**Issue by nschneid** [nert-gu/Xposition#100]
Currently there are 3 miscellaneous articles generated by LaTeX conversion (https://github.com/nert-gu/Xposition/issues/95#issuecomment-405804537).

I see a few low-level issues in these pages—not sure if they're best fixed in the LaTeX conversion or manually:

- [x] Constraints_on_Role_and_Function_Combinations: should within-page exrefs display as parenthesized numbers?
- [x] Constraints_on_Role_and_Function_Combinations: citations not rendered: "(e.g., lakoff-80, nunez-06, casasanto-08)"
- [x] Constraints_on_Role_and_Function_Combinations: numbered lists should not be headings
- [x] Special_Labels: 3 usages misrendered in (023)
- [x] Special_Constructions: citations not rendered properly in paragraph before (001), footnote 2
- [x] Basic font size should be larger as in supersense pages for readability (I'll fix this in CSS)

In addition, there are no pages for \`i, \`d, \`c to link to (these are just sections on Special_Labels), and Special_Constructions is fairly long. Can we break these 2 into separate smaller articles, and then Special_Labels and Special_Constructions would have lists of links? Will it be possible for cross-references from supersense pages to go directly to the relevant construction or special label?

**Comment by nschneid** [comment]
Everything on Special_Constructions is English-specific, so I'd put that page under /en/.

**Comment by ablodge** [comment]
(1) and (6) can be fixed in css. (3) is best fixed by hand.

**Comment by ablodge** [comment]
I think I can split up the files fairly easily and still have the links work (the links are assigned based on the latex file the `\label` appears in, so we can split the latex into separate files by hand).

**Comment by nschneid** [comment]
(1) requires a change to the macro, right?

**Comment by ablodge** [comment]
> (1) requires a change to the macro, right?
Yes.

**Comment by ablodge** [comment]
@nschneid Take a look at the [English page](http://flat.nert.georgetown.edu/en/) to see how I've set up Special Construction articles.

**Comment by nschneid** [comment]
Looks good.

**Comment by ablodge** [comment]
How do we access the current article title or slug from within the exref macro?

**Comment by nschneid** [comment]
I think you can access `self.markdown.article`.
