### ISSUE TITLE
ComparisonRef exref errors

### ISSUE THREAD

**Issue by nschneid** [nert-gu/Xposition#107]
This passage near the bottom of ComparisonRef has the wrong example numbers:

```When governed by an NP naming a category or set, like is ambiguous between exemplifying a member, as in #030 and #031, and merely indicating similarity, as in #030 and #030:```

We can fix this manually when the site goes live.

**Comment by nschneid** [comment]
Also, usage linking of gappy examples like `what_ ... _like` in ComparisonRef (025)-(027) (should go to en/what_like).

**Comment by ablodge** [comment]
Are there other gappy examples that need to be fixed by hand?

**Comment by nschneid** [comment]
Possibly! Search for space+underscore and underscore+space in the LaTeX?
