### ISSUE TITLE
Constraints on role and runction combinations 500 ERROR

### ISSUE THREAD

**Issue by ablodge** [nert-gu/Xposition#108]
Not sure what is causing this: [Constraints on role and runction combinations](http://flat.nert.georgetown.edu/constraints-on-role-and-function-combinations/)

**Comment by nschneid** [comment]
I've switched to dev mode so you can see the error: http://flat.nert.georgetown.edu/constraints-on-role-and-function-combinations/

**Comment by ablodge** [comment]
Can you delete this article and url so that I can remake it?

**Comment by nschneid** [comment]
Done
