### ISSUE TITLE
Syntactic description of 's

### ISSUE THREAD

**Issue by ablodge** [nert-gu/Xposition#109]
In streusle, the governor and object of 's are described as [GOV]'s [OBJ], which makes 's seem like a preposition instead of a post-clitic. I presume this standard comes from UD? Should we change how 's is described morphologically to match?

morphtype: _standalone preposition_ or _postfix_?
transitivity: _always transitive_ or _sometimes transitive_? (different depending on what you interpret as the object)

**Comment by nschneid** [comment]
That's not supposed to be the case: https://github.com/nert-gu/streusle/blob/f9b65d0cdce5010cb7823a599fcab7ffba41c7a4/govobj.py#L25-L28 Is there a bug in the script?

morphtype: postfix
transitivity: always transitive, in a sense that the 2nd argument in the relation is always overt (it just may be morphologically fused with the possessive marking)

**Comment by ablodge** [comment]
You know what. My mistake. After looking at it again, I think I misread some of the data.

**Comment by ablodge** [comment]
Note that for possessive pronouns like ‘my’ the ptokens are marked as intransitive and no object is listed.
