### ISSUE TITLE
PP idiom designation

### ISSUE THREAD

**Issue by nschneid** [nert-gu/Xposition#111]
I just pushed (efee7c5) an improvement to the language pages that subcategorizes the adpositions according to single-word/multiword/PP idiom and shows their transitivity.

- [x] As you can see, with the current database, most of the PP idioms are listed as transitive, but should be intransitive (as discussed in #99).

Additionally, there are borderline cases where we need a clearer definition of PP idiom vs. multiword P. (@ablodge, did you import the distinction from STREUSLE's lexcat or implement it some other way? STREUSLE may not be 100% consistent.) How about the following definition: 

> A PP idiom is a fixed or semi-fixed expression consisting of an adposition plus its complement (usually an NP, AdjP, or AdvP), which must be a complete phrase. In some of these expressions the complement may take variable modifiers (e.g., "on ONE's own"). The PP idiom as a whole does not take a complement (is intransitive). A fixed expression ending in a transitive preposition like "of" or "as" ("in search of", "as long as") requires a complement, and thus is not a PP idiom. [Infinitive marker "to" counts as a transitive preposition for purposes of this definition.]

- [x] I would say the following should be added as PP idioms:
   * in_this_day [short for "in this day and age", presumably]
   * infinitive TO+verb: to_eat, to_go

- [x] in_hope_to, just_about, nothing_but probably should not be considered PP idioms, because they are transitive.

- [x] back_and_forth (intr.), up_and_run(ning) (intr.) are listed as PP idioms whereas over_and_above (tr.) is not. My gut feeling is that neither should be considered a PP idiom. We could clarify the definition:

   > A fixed phrase with only intransitive prepositions ("back and forth", "up and run(ning)") is not a PP idiom, because there are no complements.

- [x] out_front, out_there, up_front: These seem borderline to me because they're schematic spatial descriptions. What do you think?

**Comment by nschneid** [comment]
- [ ] In the database, 's, at, and toward still have `is_pp_idiom==None`

**Comment by ablodge** [comment]
I relied on presence of an object in streusle to determine transitivity. This is an easy fix. I guess we also want to not list objects for pp idioms?

For most of these other decisions, we’ll want to edit the metadata by hand.

**Comment by ablodge** [comment]
> did you import the distinction from STREUSLE's lexcat or implement it some other way?

I just use lexcat.

**Comment by nschneid** [comment]
What problem are you encountering? I was able to edit the transitivity of "rather_than" in the metadata pane.

**Comment by ablodge** [comment]
I can't edit is_pp_idiom in the metadata (I click update and it ignores the new value). Is there something that needs to be set?

**Comment by ablodge** [comment]
I can change `is_pp_idiom` from True to False, but not False to True. I've tried several times.

**Comment by nschneid** [comment]
Oh, yes, I can reproduce that. Strange. The navlink checkbox on language articles works—is the form logic being handled in the same way?

**Comment by ablodge** [comment]
Not sure. I'm still not sure how to resolve this, but in the worst case, we can delete the adpositions 'in_this_day', 'to_go', and 'to_eat' and remake them by hand then run the importer again to re-add usages and ptokens. I've tried it locally and it works.

**Comment by ablodge** [comment]
> out_front, out_there, up_front: These seem borderline to me because they're schematic spatial descriptions. What do you think?

They meet the description of PP idioms you described above. They have to be idiomatic since they don't fit the normal gov-obj relationship for these adpositions (out there ≠ out the box). I'd prefer to keep them in pp idioms unless you can think of a good criterion to do otherwise.

**Comment by nschneid** [comment]
Aha, I think I solved the checkbox bug: `is_pp_idiom` isn't included in the set returned by `Adposition.field_names()`. This set is used by `Metadata.newRevision()` to determine which metadata fields have values to be updated.

https://github.com/nert-gu/Xposition/blob/83621db5586f9fe8f29ca6fea20fc841163c289f/wiki/plugins/metadata/models.py#L669-L672

**Comment by nschneid** [comment]
> I'd prefer to keep them in pp idioms

Fine with me.

**Comment by ablodge** [comment]
Confirmed! It works.

**Comment by ablodge** [comment]
Can you add a link to the description of PP Idioms and I'll put it in the create adposition instructions?

**Comment by nschneid** [comment]
http://flat.nert.georgetown.edu/en/pp_idioms/#wiki-toc-pp-idioms-vs-multiword-prepositions
