### ISSUE TITLE
Cannot load edit article page

### ISSUE THREAD

**Issue by nschneid** [nert-gu/Xposition#112]
E.g.:

    IndexError at /Accompanier--Accompanier/_edit/
    list index out of range

Looking at the stack trace, it seems to be coming from the categories plugin, so probably related to #97.

**Comment by ablodge** [comment]
Could we remove the categories plugin? Can you paste the stacktrace?

**Comment by ablodge** [comment]
I can replicate the problem. I have been getting IndexErrors from query.py in other contexts today (fixed with small changes). It may not be from the categories plugin. Could adding cache_properties have changed the way queries should work?

**Comment by nschneid** [comment]
Hmm...changing a `property` to a `cache_property` shouldn't cause an error (at worst it would display an old value, I think). But changing a method to a property of any kind could require a change on the caller's end.

In this case, since it's an IndexError, I suppose the problem is from `obj.article.urlpath_set.all()[0]`, indicating it's trying to display a link to a category that has no associated URL. When you unlinked usages etc. from categories is it possible that the categories were not removed from the database?

**Comment by ablodge** [comment]
Some categories stick around, like those for supersenses. You can check by clicking categories and list categories. Which fields were changed into a property?

**Comment by ablodge** [comment]
Try changing `urlpath_set.all()[0]` to `urlpath_set.all().first()`. It worked for me earlier.

**Comment by nschneid** [comment]
Ah, the problem is that categories for "'s" and "at" have stuck around despite all the other adposition categories being deleted.

**Comment by nschneid** [comment]
> Try changing `urlpath_set.all()[0]` to `urlpath_set.all().first()`. It worked for me earlier.

This displays the category name with a link to "None", which is what `first()` returns on an empty queryset.

**Comment by ablodge** [comment]
That’s definitely going to be a problem when we go live, for Korean for example.

**Comment by nschneid** [comment]
What do you mean?

**Comment by ablodge** [comment]
Any model that has been created so far will still have a category by default.

**Comment by nschneid** [comment]
Oh, since Korean data already exists. Yeah, I guess we'll need a script to remove the associated categories for adpositions, usages, and construals.

**Comment by nschneid** [comment]
(It may be doable in the admin interface; the question is whether deleting the relevant `ArticleCategory` instances would also delete the associated articles.)

**Comment by nschneid** [comment]
I see Locus--Locus in the list of stragglers, too.

**Comment by ablodge** [comment]
Just add delete_categories.py to get rid of them. It works on my end. Can you test it out?

**Comment by nschneid** [comment]
Yes, it works in the Django shell with

```py
exec(open("../scripts/delete_categories.py").read())
```

once I change the `os.chdir()` call to use a forward slash so it's Unix-compatible.

I assume for the NERT server we'll also need to delete existing usages?

**Comment by ablodge** [comment]
Yes. I wasn't sure what the category names for usages would be. Something like `at: Locus--Locus`?

**Comment by nschneid** [comment]
You can see them in the category sidebar on the NERT server. Examples included `abseits von: Locus ~> Locus` and `an<ACC>: Recipient ~> Goal`.
