### ISSUE TITLE
Upgrade the live database

### ISSUE THREAD

**Issue by nschneid** [nert-gu/Xposition#113]
@ablodge What are the steps that need to be performed once the code is synced to incorporate all the changes in #72?

**Comment by ablodge** [comment]
1. run delete_categories.py in the shell
2. I'm adding the files we need (temporarily)
3. run tex2markdown.py, add_macros.py, and construal_articles.py
4. run models_for_import.py in the shell 
5. run articles_for_import.py in the shell
6. Create STREUSLE corpus (option available in metadata under English)
7. Go to /admin/metadata/ and import construals.json, adposition_revisions.json, and corpus_sentences.json
8. go to /admin/wiki/ArticleRevisions and import supersense_article_revisions.json
9. run models_for_import.py in the shell again (needs ids for adpositions, construals)
10. run articles_for_import.py in the shell again (needs ids for construals)
11. Go to /admin/metadata/ and import usage_revisions.json
12. go to /admin/wiki/ArticleRevisions and import construal_article_revisions.json
13. run models_for_import.py in the shell again again (needs ids for adpositions, construals, usages, corpus_sentences)
14. FINALLY, Go to /admin/metadata/ and import ptoken_annotations.json, (takes about 15min)

**Comment by ablodge** [comment]
Hooray!!!
