### ISSUE TITLE
Genitives/Possessives bugs

### ISSUE THREAD

**Issue by nschneid** [nert-gu/Xposition#115]
A couple of issues on http://flat.nert.georgetown.edu/en/possessives/:

1. The citation at the beginning is linked incorrectly: the year shouldn't be parenthesized in the URL. Is that a problem on all the pages with citations?

2. The exref macro doesn't display the within-page example references in abbreviated form because the page title has a slash in it.

**Comment by nschneid** [comment]
> The exref macro doesn't display the within-page example references in abbreviated form

Likewise on http://flat.nert.georgetown.edu/en/comparatives_and_superlatives/, where it's a spaces-vs.-underscores issue.

**Comment by ablodge** [comment]
We never updated any of the misc articles. Try importing misc_article_revisions.json. If it gives errors, which it may, I'll just add the new articles by hand.

**Comment by nschneid** [comment]
> Try importing misc_article_revisions.json

Done—that uploads the 4 backtick-label articles.

**Comment by ablodge** [comment]
Just those? It's supposed to upload 13 articles.

**Comment by nschneid** [comment]
All 13 are in the JSON, but 9 show up as Skipped on the import page. Maybe `skip_row()` is matching them incorrectly?

**Comment by ablodge** [comment]
Take another look at [Genitives/Possessives](http://flat.nert.georgetown.edu/en/possessives/) to make sure everything looks good.

**Comment by nschneid** [comment]
That fixes the citation. The exrefs are still too verbose.

**Comment by ablodge** [comment]
See #120
