### ISSUE TITLE
Construal Article Bug

### ISSUE THREAD

**Issue by ablodge** [nert-gu/Xposition#116]
[Whole--Gestalt](http://flat.nert.georgetown.edu/Whole--Gestalt/) doesn't display examples correctly. Possibly a bug in the regex for this macro.

**Comment by nschneid** [comment]
Macro args should be in double quotes to avoid having to escape the apostrophe, right?

**Comment by ablodge** [comment]
This is a problem in construal_articles.py. I’ll update it.
