### ISSUE TITLE
Language pages

### ISSUE THREAD

**Issue by ablodge** [nert-gu/Xposition#117]
Adposition lists should also display the transliteration. See [Korean](http://flat.nert.georgetown.edu/ko/). Multiword adpositions should have underscores. See [abseits von](http://flat.nert.georgetown.edu/de/abseits_von/).

**Comment by nschneid** [comment]
The transliterations are apparently missing from the database. The template should display them if they're present.

**Comment by ablodge** [comment]
Weird! They are missing. Maybe during one of our migrations they were reset to the default?

**Comment by nschneid** [comment]
Hmm. I guess that could have happened if we rolled back the models to before there was a transliteration field in order to avoid migration errors with Corpus and PTokenAnnotation.

**Comment by nschneid** [comment]
Viz. problematic migration 0016: https://github.com/nert-gu/Xposition/blob/a7f050a1a6ca69e96c8c5b713cb3111a21342572/wiki/plugins/metadata/migrations/0016_auto_20180619_1912.py

**Comment by nschneid** [comment]
How should we recover them? Do you want a pre-upgrade copy of the db? It may be easier to export the transliterations by querying the database directly via SQL rather than going through Django, which would require models.py to be in sync.

**Comment by ablodge** [comment]
I figure you can run an earlier version of the database locally in a separate branch. If you can get a list of pks and transliterations from the shell, it should be easy yo update them.

**Comment by nschneid** [comment]
When we imported, were new AdpositionRevisions created for any of the adpositions that had transliterations? Or are the transliterations associated with the same AdpositionRevision ids as before?

**Comment by ablodge** [comment]
We did not add revisions to any non-English articles.

**Comment by nschneid** [comment]
66 adpositions were affected, mostly Korean & Chinese. Indexed by AdpositionRevision ID:

```py
{981: ('之间', 'zhī jiān'), 825: ('으로', 'ulo'), 824: ('대로', 'taylo'), 823: ('이라는', 'ilanun'), 822: ('이라', 'ila'), 
821: ('이라고', 'ilako'), 820: ('이고', 'iko'), 819: ('한테서', 'hanthese'), 818: ('처럼', 'chelem'), 
817: ('이면', 'imyen'), 816: ('으로써', 'ulosse'), 815: ('으로서', 'ulose'), 814: ('으로부터', 'uloputhe'), 
813: ('으로', 'eulo'), 812: ('에서부터', 'eyseputhe'), 811: ('에서', 'eyse'), 810: ('에다가', 'eytaka'), 
809: ('에다가', 'eytaka'), 808: ('에다', 'eyta'), 807: ('에다', 'eyta'), 806: ('에게서', 'eykeyseo'), 
805: ('에게', 'eykey'), 804: ('부터', 'puthe'), 803: ('보다', 'pota'), 802: ('밖에', 'pakkey'), 
801: ('만큼', 'mankhum'), 800: ('마다', 'mata'), 799: ('까지', 'kkaci'), 798: ('과', 'kua'), 
797: ('같이', 'kathi'), 796: ('에', 'ey'), 795: ('마다', 'mata'), 794: ('이면', 'imyen'), 
793: ('만큼', 'mankhum'), 792: ('으로써', 'ulosse'), 791: ('으로서', 'ulose'), 790: ('밖에', 'pakkey'), 
789: ('의', 'uy'), 788: ('을', 'ul'), 787: ('이', 'i'), 786: ('에다가', 'eytaka'), 785: ('에다', 'eyta'), 
784: ('같이', 'kathi'), 783: ('까지', 'kkaci'), 782: ('에서부터', 'eyseputhe'), 781: ('에서', 'eyse'), 
780: ('부터', 'puthe'), 779: ('으로부터', 'uloputhe'), 778: ('부터', 'pute'), 777: ('처럼', 'chelem'), 
776: ('보다', 'pota'), 775: ('한테서', 'hanthese'), 774: ('한테', 'hanthe'), 773: ('에게서', 'eykeyseo'), 
772: ('과', 'kua'), 771: ('에서', 'eseo'), 770: ('으로', 'eulo'), 650: ('由于', 'yóu yú'), 649: ('关于', 'guān yú'), 
648: ('关于', 'guān yú'), 647: ('之间', 'zhī jiān'), 646: ('之间', 'zhījiān'), 645: ('关于', 'guānyú'), 
644: ('关于', 'guanyu'), 643: ('에게', 'eykey'), 640: ('ל', 'l')}
```

**Comment by nschneid** [comment]
Transliterations restored! If the lack of underscores for German MWP names is a problem, please open another issue.
