### ISSUE TITLE
Misc construals

### ISSUE THREAD

**Issue by ablodge** [nert-gu/Xposition#119]
On the Construal List page, should special construals ('$, 'd, 'i, 'c, ??) be listed separately from other construals? I also notice that on other pages, in terms of color, they display as supersenses. See ['$](http://flat.nert.georgetown.edu/%60$/)

**Comment by nschneid** [comment]
I think the current behavior is OK. They're listed first on the construals page, so visually distinct from the others. I don't mind too much that they sometimes display as purple and sometimes as green, but I guess the `ss` macro could be updated to display all backtick-labels as purple.

**Comment by ablodge** [comment]
We could give them their own color for clarity.

**Comment by nschneid** [comment]
If you want to update the macros to give them a CSS class `misc-label`, I can give them a separate color.

**Comment by ablodge** [comment]
Okay, done.

**Comment by nschneid** [comment]
Take a look—they should all be light blue now (whether rendered from a macro, in corpus tables, or in lists of construals/usages).

**Comment by ablodge** [comment]
Cool. It looks great!
