### ISSUE TITLE
exrefs and links to Misc articles

### ISSUE THREAD

**Issue by ablodge** [nert-gu/Xposition#120]
Special Construction pages are under en/ and exrefs for them do not link properly. This should be fixed in the latex conversion and possibly also in the macro.

**Comment by ablodge** [comment]
Also, articles where the title contains special chars because of the latex conversion - [Genitives/Possessives](http://flat.nert.georgetown.edu/en/possessives/), [What counts as an adposition?](http://flat.nert.georgetown.edu/what_counts_as_an_adposition)

**Comment by ablodge** [comment]
How do you look up an article by its slug?

**Comment by nschneid** [comment]
The slug is stored on the `URLPath` pointing to the article (it's the last portion of the path).

```py
>>> URLPath.objects.filter(slug='Locus--Locus')
<URLPathQuerySet [<URLPath: en/at/Locus--Locus/>, <URLPath: en/around/Locus--Locus/>, <URLPath: en/before/Locus--Locus/>, <URLPath: en/out_of/Locus--Locus/>, <URLPath: en/on/Locus--Locus/>, <URLPath: en/in/Locus--Locus/>, <URLPath: en/out/Locus--Locus/>, <URLPath: en/away/Locus--Locus/>, <URLPath: en/within/Locus--Locus/>, <URLPath: en/back/Locus--Locus/>, <URLPath: en/by/Locus--Locus/>, <URLPath: en/outside_of/Locus--Locus/>, <URLPath: en/away_from/Locus--Locus/>, <URLPath: en/all_over/Locus--Locus/>, <URLPath: en/under/Locus--Locus/>, <URLPath: en/inside/Locus--Locus/>, <URLPath: en/between/Locus--Locus/>, <URLPath: en/in_town/Locus--Locus/>, <URLPath: en/nearby/Locus--Locus/>, <URLPath: en/in_between/Locus--Locus/>, '...(remaining elements truncated)...']>
```

To get a slug for an article:

```py
>>> a = Article.objects.get(current_revision__title='in: Locus ~> Locus')
>>> a.urlpath_set.all()[0]
<URLPath: en/in/Locus--Locus/>
>>> a.urlpath_set.all()[0].slug
'Locus--Locus'
```

**Comment by ablodge** [comment]
In reference to #121, which misc articles were skipped?

**Comment by nschneid** [comment]
Infinitive Clauses is still failing.

**Comment by ablodge** [comment]
It works!

**Comment by ablodge** [comment]
Exrefs link to deleted articles with the same title.
