### ISSUE TITLE
's construals have <GEN> in the title/URL

### ISSUE THREAD

**Issue by nschneid** [nert-gu/Xposition#121]
http://flat.nert.georgetown.edu/en/'s/

Perhaps this is because the object case is listed as genitive? I don't know if we want to say that anyway (object case is only relevant when case marking is separate from adpositions, as in German).

This breaks links from supersense pages, which have URLs without `<GEN>`.

**Comment by ablodge** [comment]
That’s because ‘s is listed as allowing gen or acc case. I can change it by modifying the metadata.

I see your point, but it seems really odd to annotate ‘my’ as accusative. English does require case for pronouns and Genitive makes more descriptive sense.

**Comment by nschneid** [comment]
With possessive pronouns the term "object case" is a misnomer, anyway. Agreed that genitive is the case of the pronoun as a whole.

**Comment by ablodge** [comment]
This relates to #109. In [NP]’s [NP], which is the object?

**Comment by nschneid** [comment]
The phrase marked by the "adposition" is the object—so the possessor.

**Comment by ablodge** [comment]
Should this be corrected in the streusle data? See #109

**Comment by ablodge** [comment]
Alright, ‘s usages may have to be deleted and re-imported to get rid of case in the url.

**Comment by nschneid** [comment]
OK, let me know what the steps are for that.

**Comment by ablodge** [comment]
0. delete json folder and run add_macros.py and construal_articles.py

**Comment by nschneid** [comment]
> Delete all 's usages and their ptokens (Not sure about the easiest way to do this; Note that if you delete it in admin, that will still leave the urls)

In the admin interface, it looks like if I delete the **article** for the usage, it will recursively delete everything that points to it. Is that what we want?

**Are you sure you want to delete the article "'s<GEN>: Time ~> Gestalt"? All of the following related items will be deleted:**
Summary

    Articles: 1
    Articles for object: 1
    Article revisions: 1
    Metadata revisions: 1
    Revision plugin revisions: 1
    Revision plugins: 1
    Article plugins: 1
    Metadatas: 1
    Usages: 1
    Adposition token annotations: 3
    Usage revisions: 1
    URL paths: 1

Objects

    Article: 's<GEN>: Time ~> Gestalt
        Article for object: 's<GEN>: Time ~> Gestalt
        Article revision: 's<GEN>: Time ~> Gestalt (1)
            Metadata revision: Metadata Revision: 's<GEN>: Time ~> Gestalt 0
                Usage revision: Usage Revision: 's<GEN>: Time ~> Gestalt 0
        Article plugin: ArticlePlugin object
        URL path: en/'s/<GEN>Time--Gestalt/
    Revision plugin revision: RevisionPluginRevision object
        Revision plugin: RevisionPlugin object
            Metadata: 's<GEN>: Time ~> Gestalt
                Usage: 's<GEN>: Time ~> Gestalt
                    Adposition token annotation: 's : streusle4.1: reviews-308088-0003
                    Adposition token annotation: 's : streusle4.1: reviews-329692-0002
                    Adposition token annotation: 's : streusle4.1: reviews-329692-0009

**Comment by ablodge** [comment]
Yes. As long as you have a way to also delete the urls afterwards.

**Comment by nschneid** [comment]
It deletes the URL paths too.

**Comment by ablodge** [comment]
Okay, but that's never worked for me before.

**Comment by nschneid** [comment]
> 0. delete json folder and run add_macros.py and construal_articles.py

Should I merge first?

**Comment by ablodge** [comment]
Yes. I’ll correct the list order.

**Comment by nschneid** [comment]
```
>>> exec(open('../scripts/add_macros.py').read().replace(r'..\scripts','../scripts'))
>>> exec(open('../scripts/construal_articles.py').read().replace(r'..\scripts','../scripts'))
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "<string>", line 16, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'markdown-and-macros'
```

**Comment by ablodge** [comment]
See the corrected list above. Make sure tex folder exists.

**Comment by nschneid** [comment]
I needed to do `os.chdir('../scripts')`

**Comment by nschneid** [comment]
OK, I'm on to step 11 of #113, and uploading `usage_revisions.json` gives an error:


Line number: 1 - Cannot resolve keyword 'adposition' into field. Choices are: article, article_id, articleplugin_ptr, articleplugin_ptr_id, created, current_revision, current_revision_id, deleted, id, metadata_ptr, metadata_ptr_id, ptokenannotation, revision_set, revisionplugin_ptr, revisionplugin_ptr_id
's, SocialRel, Gestalt, Genitive, 43, 402

Traceback (most recent call last):
File "/home/ns1057/Xposition_env/lib/python3.6/site-packages/import_export/resources.py", line 453, in import_row
instance, new = self.get_or_init_instance(instance_loader, row)
File "/home/ns1057/Xposition_env/lib/python3.6/site-packages/import_export/resources.py", line 267, in get_or_init_instance
instance = self.get_instance(instance_loader, row)
File "/home/ns1057/Xposition_env/lib/python3.6/site-packages/import_export/resources.py", line 261, in get_instance
return instance_loader.get_instance(row)
File "/home/ns1057/Xposition_env/lib/python3.6/site-packages/import_export/instance_loaders.py", line 33, in get_instance
return self.get_queryset().get(**params)
File "/home/ns1057/Xposition_env/lib/python3.6/site-packages/django/db/models/query.py", line 371, in get
clone = self.filter(*args, **kwargs)
File "/home/ns1057/Xposition_env/lib/python3.6/site-packages/django/db/models/query.py", line 784, in filter
return self._filter_or_exclude(False, *args, **kwargs)
File "/home/ns1057/Xposition_env/lib/python3.6/site-packages/django/db/models/query.py", line 802, in _filter_or_exclude
clone.query.add_q(Q(*args, **kwargs))
File "/home/ns1057/Xposition_env/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1250, in add_q
clause, _ = self._add_q(q_object, self.used_aliases)
File "/home/ns1057/Xposition_env/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1276, in _add_q
allow_joins=allow_joins, split_subq=split_subq,
File "/home/ns1057/Xposition_env/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1154, in build_filter
lookups, parts, reffed_expression = self.solve_lookup_type(arg)
File "/home/ns1057/Xposition_env/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1034, in solve_lookup_type
_, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
File "/home/ns1057/Xposition_env/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1352, in names_to_path
"Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'adposition' into field. Choices are: article, article_id, articleplugin_ptr, articleplugin_ptr_id, created, current_revision, current_revision_id, deleted, id, metadata_ptr, metadata_ptr_id, ptokenannotation, revision_set, revisionplugin_ptr, revisionplugin_ptr_id

**Comment by ablodge** [comment]
Can you paste the first usage in the json?

**Comment by nschneid** [comment]
```js
{"adposition_name": "'s", "role_name": "SocialRel", "function_name": "Gestalt", 
"obj_case": "Genitive", "adposition_id": "43", "construal_id": "402"}
```

**Comment by ablodge** [comment]
Alright. I've updated, and I have it working locally. Please merge, and start from step 9.

> 5. Follow steps 9-14 here: #113 
> 6. upload `misc_article_revisions.json` to ArticleRevisions

**Comment by nschneid** [comment]
Step 11 completed successfully; I had to break usage_revisions.json into 4 parts. 19 UsageRevisions were added.

For step 12, it is not finding any new construal articles. Is that correct? AFAICT these articles already have the correct usage links.

**Comment by ablodge** [comment]
It should be able to update all the construal articles. There are a few changes to construal pages associated with the fix for #116. If it displays “Update” instead of “Skipped” it should be working.

**Comment by nschneid** [comment]
It displays "Skipped" for all of them.

**Comment by ablodge** [comment]
Okay, sorry! I introduced a bug for construals when I fixed importing misc articles. 
Please merge, run articles_for_import.py, then step 12.

**Comment by nschneid** [comment]
Step 12: 157 new construal ArticleRevisions.

Step 14: In addition to adding the possessive tokens, it wants to update the `token_indices` fields of existing PTokenAnnotations to use space-separated indices rather than list notation. Is that correct?

**Comment by ablodge** [comment]
Yes. That’s because in our IntListField, the input is always a string and the output is always a list.

**Comment by nschneid** [comment]
All done! Everything look OK?

**Comment by ablodge** [comment]
Did you import misc_article_revisions.json?

**Comment by ablodge** [comment]
There are some exrefs and links that aren't fixed.

**Comment by ablodge** [comment]
Okay! Let's continue this on a separate issue.
