### ISSUE TITLE
Fix gappy (discontiguous) adposition examples

### ISSUE THREAD

**Issue by ablodge** [nert-gu/Xposition#122]
- [x] Frequency 004: on\_a\_ daily _basis
- [x] Manner 003: on\_ my \_own
- [x] Manner 022: on\_ the \_way
- [x] Manner 032-033: on\_a\_ bipartisan _basis

**Comment by ablodge** [comment]
See [Manner#022](http://flat.nert.georgetown.edu/Manner/#022). It's hard to see the mwe notation when a multiword adposition is underlined. Can this be fixed?

**Comment by nschneid** [comment]
If `<u>` is used only for choices in examples, you could do `u { text-decoration: none; background-color: #eee; }` to avoid underlining.

**Comment by nschneid** [comment]
BTW, [Manner#022](http://flat.nert.georgetown.edu/Manner/#022) was stubborn about misinterpreting some of the underscores as Markdown, so I replaced them with `&#95;`.

**Comment by nschneid** [comment]
I think you pushed the wrong CSS change

**Comment by ablodge** [comment]
Alright. Try it now.

**Comment by nschneid** [comment]
👍
