### ISSUE TITLE
other_forms when editing adposition metadata should default to space separated

### ISSUE THREAD

**Issue by ablodge** [nert-gu/Xposition#125]
If I edit metadata of toward or 's, the default is to display the previous value of other_forms as a list (`['towards']`). Remember that our StringListField always takes a string and returns a list. If you don't change the field by hand, you end up with a confused value: `["['towards']"]`. Any way to fix this?

**Comment by nschneid** [comment]
The form field issue is tricky: it seems that the custom model field (`StringListField`) methods for serializing/deserializing are not called by the form field. Probably it requires custom logic in the form, or a custom form field to go along with the custom model field.

**Comment by nschneid** [comment]
What do you think of the above? Do we want to prevent sequences of multiple spaces from yielding empty-string entries in the list? If so, `split()` with no arguments will collapse them.

**Comment by ablodge** [comment]
Looks good. Yes, collapsing multiple spaces would be ideal.

**Comment by nschneid** [comment]
Should be working now on the server.
