### ISSUE TITLE
Interlinear gloss tweaks

### ISSUE THREAD

**Issue by nschneid** [nert-gu/Xposition#131]
They're looking great! Just a couple things:

- [x] `<br>` is displaying on the server: http://flat.nert.georgetown.edu/he/%D7%9C/ I double-checked that base.py includes it in the whitelist. Any idea what might be going on?

- [x] Could you add the CSS class `example` alongside `interlinear`?

**Comment by ablodge** [comment]
`<br>` is fed as an argument to the macro, so it's being html escaped, right? Is there a way around this?

**Comment by nschneid** [comment]
Is it possible only to escape the parts inside `{...}`? Maybe by tweaking https://github.com/nert-gu/Xposition/pull/129/files#diff-53ef184a129d8b895c218d8070b610f4R251?

**Comment by ablodge** [comment]
Try this.

**Comment by nschneid** [comment]
Voilà!
