### ISSUE TITLE
Error when creating a new construal

### ISSUE THREAD

**Issue by dhwang90** [nert-gu/Xposition#134]
Tried creating a new construal, and I ran into an error.

=== ERROR ===

Request Method: | POST
-- | --
http://flat.nert.georgetown.edu/ko/%EC%97%90%EA%B2%8C/_plugin/metadata/createconstrual/
1.11.14
IntegrityError
UNIQUE constraint failed: wiki_urlpath.site_id, wiki_urlpath.parent_id, wiki_urlpath.slug
/home/ns1057/Xposition_env/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py in execute, line 328
/usr/bin/python3
3.6.0
['/home/ns1057/Xposition_env/Xposition/testproject',  '/home/ns1057/Xposition_env/lib/python36.zip',  '/home/ns1057/Xposition_env/lib/python3.6',  '/home/ns1057/Xposition_env/lib/python3.6/lib-dynload',  '/opt/anaconda3/lib/python3.6',  '/home/ns1057/Xposition_env/lib/python3.6/site-packages',  '/home/ns1057/Xposition_env/Xposition/testproject/testproject',  '/home/ns1057/Xposition_env/Xposition/testproject',  '/home/ns1057/Xposition_env/lib/python3.6/site-packages/odf',  '/home/ns1057/Xposition_env/lib/python3.6/site-packages/odf',  '/home/ns1057/Xposition_env/lib/python3.6/site-packages/odf',  '/home/ns1057/Xposition_env/lib/python3.6/site-packages/odf',  '/home/ns1057/Xposition_env/lib/python3.6/site-packages/odf',  '/home/ns1057/Xposition_env/lib/python3.6/site-packages/odf',  '/home/ns1057/Xposition_env/lib/python3.6/site-packages/odf']
Tue, 31 Jul 2018 11:02:31 -0400

**Comment by ablodge** [comment]
@dhwang90 Which construal did you try to create?

This error implies that the urlpath is already taken. It might be left over from a deleted construal.

**Comment by dhwang90** [comment]
@ablodge it was either Agent ~> Source or Agent ~> Goal.

**Comment by nschneid** [comment]
Agent ~> Source already exists and is used in English. Did you mean to create a usage?

**Comment by nschneid** [comment]
@ablodge is it possible to either give a proper validation error message when attempting to create a duplicate construal, or simply redirect to the existing page?

**Comment by dhwang90** [comment]
oh hmm, i think i must just have missed the "Agent ~> Source" construal in the list and tried to create a new one. It would definitely be nice if it would just say that it exists.

**Comment by ablodge** [comment]
We can use a [Validator](https://docs.djangoproject.com/en/2.0/ref/validators/).

**Comment by dhwang90** [comment]
Oh wait, the error is from the Usage window. If i try to create a usage of Agent->Source i get that error. Sorry, I had the wrong functionality in my head.

**Comment by dhwang90** [comment]
I get the same error for Theme--Goal

**Comment by ablodge** [comment]
Oh that’s weird. Do we have the same problem with other Korean adpositions?

**Comment by dhwang90** [comment]
I briefly did with Experiencer-Theme I think it was, but then i tried again, and it didn't error. I have failed to replicate it.

**Comment by dhwang90** [comment]
Okay I think this is resolved. It turns out the error was happening for only one of the two postpositions that can have Agent--Source usage. So i just edited the URL corresponding to what the URL would be if there were an Agent--Source page for the erroring postposition. That got me to a deleted page with the option of restoring the deleted page. That did the trick.
