### ISSUE TITLE
construal count shown is wrong

### ISSUE THREAD

**Issue by dhwang90** [nert-gu/Xposition#135]
ON: http://flat.nert.georgetown.edu/ko/
It says, the parentheses are supposed to show the construal count. Take a look at 

한테 hanthe (7) http://flat.nert.georgetown.edu/ko/%ED%95%9C%ED%85%8C/
한테서 hanthese (4) http://flat.nert.georgetown.edu/ko/%ED%95%9C%ED%85%8C%EC%84%9C/

The first has 3 contruals, and second has 1 construal. They show up as 7 and 4.

**Comment by nschneid** [comment]
Yep this is #130.
