### ISSUE TITLE
Bug in new Markdown macros?

### ISSUE THREAD

**Issue by nschneid** [nert-gu/Xposition#15]
After merging #14 and deploying, I tested the macros at the beginning of http://flat.nert.georgetown.edu/Locus--Locus/ and it seems the last one on the line is clobbering the rest of the line.

**Comment by ablodge** [comment]
Yeah, that doesn’t really make sense to me but I’ll debug it.

**Comment by ablodge** [comment]
On running `python manage.py runserver` I get:
`Replacing existing 'hilite' extension - please remove 'codehilite' from WIKI_MARKDOWN_KWARGS`

Any idea what this means?

**Comment by ablodge** [comment]
Okay I got it working. Run the server when you can.

**Comment by nschneid** [comment]
Still not working for http://flat.nert.georgetown.edu/Locus--Locus/

It looks like it may be creating a single link by matching from the first `[` to the last `]` in the line. The regexes may need to use non-greedy operators: note that, for example, `a.*b` will match from with the first `a` and last subsequent `b`. The non-greedy `*?` and `+?` operators avoid this: `a.*?b` matches from the first `a` to the first subsequent `b`.

**Comment by nschneid** [comment]
But also keep in mind the effects on nested macros, if we need to be able to parse those.

**Comment by ablodge** [comment]
This should work

**Comment by ablodge** [comment]
I still need to test nested macros, but the design I put in will allow them.
