### ISSUE TITLE
Add style to following CSS classes

### ISSUE THREAD

**Issue by ablodge** [nert-gu/Xposition#20]
Add style to following CSS classes:
supersense
construal
usage
adpostion
example
exref - link to example
misc - anything with `

**Comment by ablodge** [comment]
Where to put style sheet?

**Comment by nschneid** [comment]
Maybe in https://github.com/nert-gu/Xposition/blob/master/wiki/plugins/metadata/static/wiki/css/metadata.css

**Comment by ablodge** [comment]
The style features look great! 

@nschneid Could you change _adpostion_ style to a lighter shade of red? It looks a little like a broken link.
