### ISSUE TITLE
Uniqueness failure when saving edits to article for a usage

### ISSUE THREAD

**Issue by nschneid** [nert-gu/Xposition#25]
e.g. http://flat.nert.georgetown.edu/en/near/Locus--Locus/

UNIQUE constraint failed: metadata_usagerevision.adposition_id, metadata_usagerevision.obj_case, metadata_usagerevision.construal_id

Unclear why revision_number isn't showing up in the constraint; cf. https://github.com/nert-gu/Xposition/blob/master/wiki/plugins/metadata/models.py#L610 (maybe the constraint was modified and the modification didn't make its way into the database?)

**Comment by ablodge** [comment]
I've replicated this behavior on the site (errors for editing or deleting). But when running locally, everything works fine.

**Comment by nschneid** [comment]
The new migrations include

```py
migrations.AlterUniqueTogether(
            name='usagerevision',
            unique_together=set([]),
        )
```

I'm not sure why this is happening, but it may have to do with custom uniqueness validation code for `MetadataRevision` subclasses. I think this is telling Django not to use its normal `unique_together` list under the `Meta` inner class.

Anyway, let me see if I can get this to work....

**Comment by nschneid** [comment]
Now working on the server
