### ISSUE TITLE
Remove deleted construals from choice field

### ISSUE THREAD

**Issue by nschneid** [nert-gu/Xposition#28]
Similar to #9, which was about deleting usages, we should consider the implications of deleting a construal. If a construal is deleted but not purged from the DB, will it still be listed as an option when creating a usage?

**Comment by ablodge** [comment]
Deleted construals do show up as an option. Maybe we can set some feature of the model to fix this?

**Comment by ablodge** [comment]
Added the following line to UsageForm
`self.fields['construal'].choices = [(construal.id,str(construal)) for construal in models.Construal.objects.filter(article__current_revision__deleted=False)]`
