### ISSUE TITLE
AttributeError: 'Language' object has no attribute 'current_revision'

### ISSUE THREAD

**Issue by nschneid** [nert-gu/Xposition#29]
https://github.com/nert-gu/Xposition/blob/449a1a248e093e03ca019d538e20cf080f657efe/wiki/plugins/metadata/templatetags/metadata_tags.py#L69

**Comment by nschneid** [comment]
`lang.article.deleted`?

**Comment by nschneid** [comment]
This is because `Language`s and `Construal`s don't have metadata revisions. (They simply point to an article which has revisions.) So several of the template tags are buggy.

**Comment by ablodge** [comment]
`construal.article.deleted` gives a field error

**Comment by ablodge** [comment]
Okay, I got it
