### ISSUE TITLE
AttributeError when using 'Settings' locally

### ISSUE THREAD

**Issue by ablodge** [nert-gu/Xposition#31]
AttributeError: type object 'Settings' has no attribute 'all'

**Comment by ablodge** [comment]
I’m not sute if this is important as it may not be replicated on the site. [close if you find that it’s not replicable]

**Comment by nschneid** [comment]
What triggered the error?

**Comment by ablodge** [comment]
Clicking ‘settings’ on the start page

**Comment by nschneid** [comment]
OK. I encountered that after updating to a version of Django that was newer than what django-wiki supported  (as of when we forked from it). The server has a suitably old version of Django.
