### ISSUE TITLE
Create (and Upload) Example objects

### ISSUE THREAD

**Issue by ablodge** [nert-gu/Xposition#32]

**Comment by ablodge** [comment]
@nschneid What are the relevant python files for this update?

**Comment by ablodge** [comment]
Error: django.db.utils.OperationalError: table "metadata_corpus" has more than one primary key

**Comment by nschneid** [comment]
Yep you found where the models live. http://django-import-export.readthedocs.io/ may be a good way to implement the import/export (I think it can hook into the database admin interface, so you don't have to implement your own UI for import/export).

**Comment by nschneid** [comment]
Since I rebased master, I think you'll need to create a new branch to replace xposition-data so changes can be merged properly.

**Comment by ablodge** [comment]
@nschneid Should the new plugin be added to `wiki/tests/settings.py` or `testproject/testproject/settings/base.py` and what's the difference?

**Comment by ablodge** [comment]
I fixed Migrations by keeping the `DeleteModel` commands and getting rid of the `RemoveField` commands which seem to be redundant

**Comment by ablodge** [comment]
On importing data that references a non-existent model, django displays this:

`Line number: 1 - Adposition matching query does not exist.`

**Comment by nschneid** [comment]
I assume missing adpositions will need to be created manually? It would be nice if it could display a list of the missing adpositions in the data.

For missing construals and usages, perhaps they can be created automatically on import.

**Comment by nschneid** [comment]
A couple of requests for models.py:

- [ ] Use the technique at https://stackoverflow.com/a/1113039 so that accessing `sentence.tokens` gives a list rather than a string
- [ ] Add `gov_head_index` and `obj_head_index` (integers)

**Comment by ablodge** [comment]
Also:
- [ ] Add import feature for BitField `obj_cases` in `AdpositionRevision`. Do you know how these are stored, if there is an easy way to instantiate them?

**Comment by ablodge** [comment]
Error:
```
Template error:
In template C:\Users\Austin\Desktop\Xposition\local\Xposition\testproject\testproject\templates\wiki\base_site.html, error at line 16
   'Construal' object has no attribute 'ptokenannotation'   6 :     <meta name="viewport" content="width=device-width, initial-scale=1.0">
   7 :     <meta http-equiv="X-UA-Compatible" content="IE=edge">
   8 :     <meta name="description" content="">
   9 :     <meta name="author" content="www.django-wiki.org">
   10 : 
   11 :     <!-- Le styles -->
   12 :     <link href="{% static "wiki/bootstrap/css/wiki-bootstrap.min.css" %}" rel="stylesheet">
   13 : 
   14 :     {% render_block "css" %}
   15 : 
   16 :     <!-- Le HTML5 shim, for I E6-8 support of HTML5  elements -->
   17 :     <!--[if lt IE 9]>
   18 :       <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
   19 :     <![endif]-->
   20 : 
   21 :   </head>
   22 : 
   23 :   <body>
   24 : 
   25 :     {% block wiki_body %}
   26 : 


```
