### ISSUE TITLE
List of supersenses is empty

### ISSUE THREAD

**Issue by nschneid** [nert-gu/Xposition#33]
http://flat.nert.georgetown.edu/supersenses/

possibly affected by https://github.com/nert-gu/Xposition/commit/50ab235f1f1593d0e9f16e8d6d9517b87086a3d3#diff-c046c6e9a7b8128d35d2ba8f29de55e7R132

**Comment by ablodge** [comment]
Alright. That's strange, but we probably don't need that line of code.

**Comment by nschneid** [comment]
Fixed!
