### ISSUE TITLE
`p` macro duplicates construal in URL

### ISSUE THREAD

**Issue by nschneid** [nert-gu/Xposition#37]
In the first example of http://flat.nert.georgetown.edu/Locus--Locus/, `[p en/next_to Locus--Locus]` is being mapped to the URL /en/next_to/Locus--Locus--Locus--Locus. The duplication of the 2nd argument should only happen if it is a supersense rather than a construal, i.e., lacks `--`.

**Comment by ablodge** [comment]
wiki/plugins/macros/mdx/macro.py line 118
