### ISSUE TITLE
Conversion from LaTeX: use underscores instead of hyphens for MW preps

### ISSUE THREAD

**Issue by nschneid** [nert-gu/Xposition#43]
E.g. http://flat.nert.georgetown.edu/Accompanier/ should mention "in_addition_to" etc.

**Comment by ablodge** [comment]
Do you have ideas for converting latex `\ref`s? For example, I need to convert `\ref{ex:pathmanner}` to `[exref ### Path]`.

**Comment by ablodge** [comment]
I also need to convert \citet{person2018} to a bib citation. Is there any automatic way to do this?

**Comment by nschneid** [comment]
I doubt the bibliography will change much, so you can probably manually create an article for each citation, e.g. http://flat.nert.georgetown.edu/bib/person2018 (using the cite key as the slug). Not worth trying to parse BibTeX automatically.

**Comment by nschneid** [comment]
But if you use the cite key, convert it to all caps so it doesn't look as weird at the beginning of a sentence: `[bib/BLODGETT18](BLODGETT18)`
