### ISSUE TITLE
Make Sentence View

### ISSUE THREAD

**Issue by ablodge** [nert-gu/Xposition#46]
We need to add a non-article view for `CorpusSentence`s

**Comment by nschneid** [comment]
One thought: a URL path like /en/corpus/streusle4.1/reviews-001325-0003 displays the sentence with clickable PTokenAnnotation targets. 

- Hovering on a word (eventually, perhaps including non-targets) displays a tooltip with its POS and supersense, if applicable. 
- Clicking on a target or supplying a hash in the URL like /en/corpus/streusle4.1/reviews-001325-0003#5 displays metadata for the annotation and causes the target, its governor, and its object to be highlighted. 
- Double-clicking the target navigates to the page for the usage.

Perhaps there should also be a toggle option to display all supersenses inline with the text.

**Comment by nschneid** [comment]
Simpler design: just display 
- the sentence with each adposition linked to a usage page and its construal displayed inline as a subscript, and
- the table with all PTokenAnnotations in the sentence.

**Comment by ablodge** [comment]
How do I set the url pattern?

**Comment by nschneid** [comment]
With a regex in https://github.com/nert-gu/Xposition/blob/master/wiki/plugins/metadata/urls.py

**Comment by ablodge** [comment]
I added the following:
```
#urls.py

urlpatterns = [
  ...
  url(r'^corpussentence/$', views.CorpusView.as_view(), name='corpus_sentence_view'), 
]
```
Django can't seem to detect any url I use.

**Comment by nschneid** [comment]
I seem to recall that there's a urls.py for the site overall which is processed first, and this urls.py is for customizations. I'll take a look later today and try to figure it out.

**Comment by nschneid** [comment]
OK it appears https://github.com/nert-gu/Xposition/blob/master/wiki/urls.py#L221 loads the custom urls.py for the metadata plugin and appends the pattern to /_plugin/metadata or /<article>/_plugin/metadata. Which is fine for the forms to create supersenses etc. (the URL doesn't much matter), but for corpus sentences/annotations we want a simpler URL. So it may require changes in the core django-wiki code.

**Comment by nschneid** [comment]
I think we're in good shape for this and #61—please verify on your end, e.g. with URLs /ex/3495/ and /en/corpus/streusle4.1/reviews-010378-0002/

The one thing that's not working correctly for me is the URL of the article associated with the CorpusSentence. It should be /en/corpus/streusle4.1, but right now it's just streusle4.1. I assume this needs to be changed in the database (or maybe you've already changed it in the database).

**Comment by ablodge** [comment]
Yes, the Corpus article and category need to have its language set as the parent and the slug adjusted. I'll fix forms.py accordingly.

**Comment by ablodge** [comment]
I got everything to work without /corpus/ in the url, as in:
/ex/3495/
/en/streusle4.1/reviews-010378-0002/

We might create a separate issue for changing to /en/corpus/streusle4.1/ as django seems to want a parent article at /en/corpus/ which I haven't figured out how to do from form.

**Comment by nschneid** [comment]
I don't necessarily object to dropping /corpus from the URL. It would mean adpositions and corpora live under the same parent, but I think we can avoid conflicts by making sure corpus names include a version number.

**Comment by ablodge** [comment]
I had to change the url pattern for corpus_sentences to `en/corpus/~/sent_id` to avoid collision with the usage url pattern.

**Comment by ablodge** [comment]
See #91 for further issues
