### ISSUE TITLE
Create Import Resource for Adpositions, Construals, Usages

### ISSUE THREAD

**Issue by ablodge** [nert-gu/Xposition#50]
In order to import `PTokenAnnotation` objects, the `Adposition`s they reference need to be imported first. Should I import `Adposition`s, `AdpositionRevision`s, or both?

**Comment by nschneid** [comment]
See my comment in #32. To create an adposition you need to know whether it is always transitive or not. I suspect this should be done manually.

**Comment by ablodge** [comment]
@nschneid For dealing with Revisions, what do I need to know about creating them? Is there a function I can call like `AdpositionForm.new()` that will handle the details?

**Comment by nschneid** [comment]
I guess the main thing to keep in mind is that you have to instantiate models for `AdpositionRevision` and `Adposition`, as well as a corresponding article, and a corresponding category. `AdpositionForm` is a `ModelForm`, so it's automatically tied to the `AdpositionRevision` instance—the `m` argument to `new()`.

**Comment by ablodge** [comment]
Then probably what makes the most sense to to import the Adposition and include code that will create the revision, article, and category.

What is the category? Is there an example in `AdpositionForm`?

**Comment by ablodge** [comment]
How do I handle:
```
'owner': self.request.user,
'group': self.article.group,
'group_read': self.article.group_read,
'group_write': self.article.group_write,
'other_read': self.article.other_read,
'other_write': self.article.other_write,
```

**Comment by nschneid** [comment]
Those are user permissions. I guess you can designate the person who does the import (admin user?) as the owner. The group etc. should be the same as other English adposition articles—maybe the import script can look up an existing one and copy them.

**Comment by ablodge** [comment]
Is there a standard way to access them without a Form object?

**Comment by nschneid** [comment]
I'm not sure how to access the current user. To copy the permissions of an existing article, probably the best way is `Article.get(...).group` etc.

**Comment by ablodge** [comment]
@nschneid If you have time, can you review my code for wiki/admin.py and think about what we can do about the `#TODO` cases?

**Comment by ablodge** [comment]
How do I set a revision number?
```
Line number: 1 - NOT NULL constraint failed: wiki_revisionpluginrevision.revision_number 
Goal, , Goal
Traceback (most recent call last):
File "C:\Users\Austin\Anaconda3\lib\site-packages\django\db\backends\utils.py", line 64, in execute
return self.cursor.execute(sql, params)
File "C:\Users\Austin\Anaconda3\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: wiki_revisionpluginrevision.revision_number
```

**Comment by nschneid** [comment]
> How do I set a revision number?

See https://github.com/nert-gu/Xposition/blob/ab2dbdc848df2d45829ed2e9165f469dc59d261b/wiki/models/article.py#L161

**Comment by nschneid** [comment]
BTW, if you send me a version of the database with a few tokens imported (even if import isn't fully working), this week I may have time on the plane to hack on the display of tokens in the existing views (supersense, adposition, construal, usage, corpus). I realize you're busy this week, though!

**Comment by ablodge** [comment]
Imports that work so far:
`CorpusSentence`✔
`PTokenAnnotation`✔
`Supersense` (for testing/debugging)
`Adposition`
`Construal`
`Usage`

**Comment by ablodge** [comment]
Imports that work so far:
`CorpusSentence`✔
`PTokenAnnotation`✔
`SupersenseRevision` (for testing/debugging)
`AdpositionRevision`
`Construal`✔
`UsageRevision`

**Comment by ablodge** [comment]
Imports that work so far:
`CorpusSentence`✔
`PTokenAnnotation`✔
`SupersenseRevision`✔ (for testing/debugging)
`AdpositionRevision`
`Construal`✔
`UsageRevision`

`AdpositionRevision` adds faulty url `en/for//en/for/` to slug.

**Comment by ablodge** [comment]
Imports work for:
`CorpusSentence`✔
`PTokenAnnotation`✔
`SupersenseRevision`✔ (for testing/debugging)
`AdpositionRevision`✔
`Construal`✔
`UsageRevision`✔

Hooray!
