### ISSUE TITLE
LaTeX conversion: '%' comments

### ISSUE THREAD

**Issue by nschneid** [nert-gu/Xposition#54]
When processing LaTeX, everything from comment marker `%` to the end of the line should be removed, including the line break. Thus

```tex
not really possessives---% 
e.g. 
```

should render as "not really possessives—e.g." in http://flat.nert.georgetown.edu/special-constructions/.

**Comment by nschneid** [comment]
Looks like it's a problem at Time: "Time— unlike" shouldn't have a space. I can't find the Special_Constructions page.

**Comment by ablodge** [comment]
Should there never be a space if the comment is removed?

**Comment by nschneid** [comment]
Not sure what you mean about "removed". If there is a text character followed immediately by comment `%`, and the next line of the source starts with a text character, or with an inline text macro like `\footnote{}`, there should be no space between them. (I'm not sure what the rule is if the next line of source starts with `%`, but that shouldn't matter for the guidelines document.)

**Comment by ablodge** [comment]
Okay, there is actually no space in the markdown, but there is a new line. The display adds the space when it concatenates the lines.
