### ISSUE TITLE
Supersense pages: missing short description at the top of the page

### ISSUE THREAD

**Issue by nschneid** [nert-gu/Xposition#76]
It's not getting extracted from the LaTeX, presumably?

**Comment by ablodge** [comment]
It’s displayed in the markdown page between vertical bars. I articles_for_import.py not to update it because 1) not all articlerevisions have those, and 2) ours are already online.

Did you update them in the new guidelines?

**Comment by ablodge** [comment]
TODO update:
Approximator
Co-Agent
Co-Theme
Configuration
Gestalt
Possession
Recipient
Species
Stuff

(mostly minor changes)

**Comment by ablodge** [comment]
The description feature on Supersense articles isn't long enough to hold some of the full descriptions. We should change the max_length to 300 and migrate.

**Comment by nschneid** [comment]
I've applied the migration as 0021 (after faking migrations 0019 and 0020). See if the longer description works.

**Comment by ablodge** [comment]
I get

> Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.
Please contact the server administrator at [no address given] to inform them of the time this error occurred, and the actions you performed just before this error.
More information about this error may be available in the server error log.

**Comment by nschneid** [comment]
I've enabled dev mode, so try again to see the error.

**Comment by ablodge** [comment]
> OperationalError
attempt to write a readonly database

**Comment by nschneid** [comment]
Oops. Try again.

**Comment by ablodge** [comment]
Works!
