### ISSUE TITLE
LaTeX conversion: "toward(s)" should link to "toward" adposition/usage

### ISSUE THREAD

**Issue by nschneid** [nert-gu/Xposition#79]
E.g. Goal in the sentence before (013)

**Comment by nschneid** [comment]
Source has "off_(of)" and "out_(of)". I guess these can be converted to "off/off_of" and "out/out_of" for proper linking.

**Comment by ablodge** [comment]
It looks like there are only the three cases: `[toward(s)](/en/toward(s))`, `[off(_of)](/en/off(_of))`, and `[out(_of)](/en/out(_of))`

I can hardcode replacement links for these three.
