### ISSUE TITLE
LaTeX conversion: Set of subexamples introduced with a supersense/construal

### ISSUE THREAD

**Issue by nschneid** [nert-gu/Xposition#80]
Manner has several of these, e.g.:

```tex
\ex \rf{Manner}{ComparisonRef}:\begin{xlist}
      \ex You eat \p{like} a pig (eats).
      \ex You smell \p{like} a pig.
    \end{xlist}
```

This may require parsing sub-example structure, unfortunately.

**Comment by nschneid** [comment]
If it's easiest to flatten all the nested lists and display these as

- Sentence1 (Construal)
- Sentence2 (Construal)

I think that's OK, so long as the usage links are correct.

**Comment by ablodge** [comment]
Yeah, it's much easier to flatten them. Are there any cases in Manner where the usage is wrong?

**Comment by nschneid** [comment]
Yeah, right now the above are still showing up as /en/like/Manner--Manner, when they should be /en/like/Manner--ComparisonRef.

**Comment by ablodge** [comment]
Okay. I fixed this issue and the current code can do either with or without indentation of sublists or subsublists etc. It looks to me like the article with no indentation looks much nicer.

@nschneid I sent you the new db. Please double check that the usages are the way they should be. I also sent the Manner article with indentation so you can compare them. See if you agree with me on which looks nicer.

**Comment by nschneid** [comment]
On the Manner page I see one link issue: the usage in 006.

**Comment by nschneid** [comment]
I think I prefer it with indentation, because that better respects the structure of the original document and shows which examples are most closely related. There are some places where the indentation is missed, though: "With the noun state, condition, etc.:" should be indented at a deeper level, as should the list under "State PPs with complements.".

**Comment by ablodge** [comment]
Okay. This was really difficult to implement! Please, no one break it.

**Comment by ablodge** [comment]
There are still some bugs. Let me know if you see any degenerate markdown.

**Comment by nschneid** [comment]
Characteristic has a bunch of cases that mention a supersense or construal followed by a sublist. In some of them the correct annotation is just Characteristic. Maybe a good heuristic is that if the text introducing a sublist begins or ends (ignoring punctuation) with a supersense/construal, then that should be the default for examples in the sublist. Otherwise, it is likely just a mention.

The latest version of Manner looks pretty good. 032-033 need to be indented, and there's a problem with the first couple of footnotes.

**Comment by nschneid** [comment]
In Theme, there are a bunch of cases with an example and more examples indented underneath it. Since we're not displaying sentences with subnumbers, like (14a), this looks odd. So maybe if there's an `\ex\begin{xlist} ...`, it should not trigger a new level of indentation (as opposed to `\ex blah blah\begin{xlist}`).

**Comment by nschneid** [comment]
Regarding multicolumn example lists, note that `\sn` is equivalent to `\ex` but doesn't print an example number. For some of these lists, both columns have an `\sn` at the top which indicates the construal for the column.

**Comment by ablodge** [comment]
I changed the heuristic for construals of sublist items to only look at construal refs at the start or end of a line.

I automatically flatten sublists whose parent is an example.
