### ISSUE TITLE
LaTeX conversion: lingering backslashes

### ISSUE THREAD

**Issue by nschneid** [nert-gu/Xposition#82]
- Under Circumstance, there are a few that originated as `\\` or `\\{}` line breaks or `\ ` (escaped space = normal size space). Maybe there's a way to check that no visual backslashes remain after the Markdown is rendered?
- Under Whole, the 's examples appear in the Markdown like `[ex 010 'the car[p en/\\'s Whole] new engine']`, which breaks the macro. It should be `[ex 010 'the car[p en/\'s Whole] new engine']`, the single backslash escaping the quoted string argument to the macro.

**Comment by nschneid** [comment]
ComparisonRef also has a bunch of visible backslashes towards the bottom.

**Comment by nschneid** [comment]
Would it make sense to change the macros to take double-quoted strings instead of single-quoted strings, so it could just be `[ex 010 "the car[p en/'s Whole] new engine"]`? I would guess that there are fewer double quotes in the examples that would need escaping.

**Comment by ablodge** [comment]
Good idea! It is done.

**Comment by nschneid** [comment]
What about the first category of extra backslashes?

**Comment by nschneid** [comment]
Never mind—see my comments in c4acea9.
