### ISSUE TITLE
Styling of macro-generated examples within articles

### ISSUE THREAD

**Issue by nschneid** [nert-gu/Xposition#90]
This is cosmetic, but I think I'd prefer removing the quotes (examples are already distinguished by font weight) and deemphasizing the example numbers.

**Comment by nschneid** [comment]
@ablodge What do you think?

**Comment by nschneid** [comment]
I think the LaTeX conversion shouldn't insert parentheses around exrefs. If we want to display parentheses we can do that with CSS, but I don't think they're necessary.

**Comment by ablodge** [comment]
The hover-over highlighting looks great! I agree that exrefs don't need parentheses. 

You can try to fix the highlighting in construal pages.
It's not obvious that the examples and text are a different font style. Maybe the examples should be slightly smaller, which would make it visually easier to pick out the text.

**Comment by ablodge** [comment]
Looks good!

**Comment by nschneid** [comment]
With the new database, exrefs have parentheses on construal pages like Manner--Stuff.

**Comment by ablodge** [comment]
Fixed. (I just hadn't uploaded new construal articles in a while)
