### ISSUE TITLE
CorpusSentence url pattern should require at least one number

### ISSUE THREAD

**Issue by ablodge** [nert-gu/Xposition#91]
See #46

**Comment by ablodge** [comment]
Is it possible to move the corpus_sentence url ahead of the usage url in terms of priority? (So the corpus_sentence is called if there is a number)

**Comment by ablodge** [comment]
I am still confused about
- [ ] how to require that a field does or doesn’t contain a number
-[ ] how to change the order of url patterns to put corpus sentences first

**Comment by nschneid** [comment]
> how to change the order of url patterns to put corpus sentences first 

What about flipping the order of the concatenation here: https://github.com/nert-gu/Xposition/blob/0e1ee44cc0aaa35430400680d561c7bea1600002/wiki/plugins/metadata/urls.py#L15

**Comment by ablodge** [comment]
Alright. I changed the url pattern. I also changed `Corpus.__str__()` to `name.lower()+version` to match its slug pattern. I hope that's alright.

The last thing is to require that adposition fields can't contain a number and that version fields must contain a number. We might do this by raising an exception in the form object. I've seen cases where these are displayed in html. Is there a standard way to do this?

**Comment by ablodge** [comment]
There is a form function `validator()` I think for that purpose.

**Comment by nschneid** [comment]
https://docs.djangoproject.com/en/2.0/ref/forms/fields/#regexfield may help

**Comment by ablodge** [comment]
The field name isn't filled in for adpositionrevision. It inherits from metadatarevision. Any ideas on how to modify it?

**Comment by nschneid** [comment]
Oh right. Maybe define `clean_name()`? https://docs.djangoproject.com/en/2.0/ref/forms/validation/

**Comment by nschneid** [comment]
Hang on. Is it the `name` that matters, or the `slug`? The slug is already prevented from containing most nonalphanumeric characters, because it has to go in the URL. In the `AdpositionForm` definition:

https://github.com/nert-gu/Xposition/blob/4cdbd9b47bb0372b363834b3684a0a523d54c833/wiki/plugins/metadata/forms.py#L325-L332

I don't exactly remember the relationship between the name and the slug. It may be that the slug is filled in automatically with Javascript as the name is typed in, and slug-unworthy characters are ignored.

**Comment by ablodge** [comment]
`UNICODE_LETTERS_NUMERICS_HYPHEN_APPOS` is defined on line 97 as a long unicode literal:


```
UNICODE_LETTERS_NUMERICS_HYPHEN_APPOS = (
    r'^[-_\'\u0041-\u005A\u0061-\u007A\u00AA\u00B5\u00BA\u00C0-\u00D6\u00D8-\u00F6'
    r'\u00F8-\u02C1\u02C6-\u02D1\u02E0-\u02E4\u02EC\u02EE\u0370-\u0374'
    r'\u0376-\u0377\u037A-\u037D\u0386\u0388-\u038A\u038C\u038E-\u03A1'
    r'\u03A3-\u03F5\u03F7-\u0481\u048A-\u0523\u0531-\u0556\u0559\u0561-\u0587'
    r'\u05D0-\u05EA\u05F0-\u05F2\u0621-\u064A\u066E-\u066F\u0671-\u06D3\u06D5'
    r'\u06E5-\u06E6\u06EE-\u06EF\u06FA-\u06FC\u06FF\u0710\u0712-\u072F'
    r'\u074D-\u07A5\u07B1\u07CA-\u07EA\u07F4-\u07F5\u07FA\u0904-\u0939\u093D'
    r'\u0950\u0958-\u0961\u0971-\u0972\u097B-\u097F\u0985-\u098C\u098F-\u0990'
    r'\u0993-\u09A8\u09AA-\u09B0\u09B2\u09B6-\u09B9\u09BD\u09CE\u09DC-\u09DD'
...
```
How do I redifine this?

**Comment by ablodge** [comment]
I think implementing `clean_name()` may be easier.

**Comment by ablodge** [comment]
Oh I see what you mean! Actually I've tried writing a url with a number and it looks to be blocked already.

**Comment by ablodge** [comment]
Yeah confirmed. I'm not sure why but you cannot create an adposition with a number digit (although the message claims that you can use numbers).

**Comment by ablodge** [comment]
Okay! Everything works.
