### ISSUE TITLE
More style fixes

### ISSUE THREAD

**Issue by ablodge** [nert-gu/Xposition#92]
Can we:
- [x] make the exref links the same size and font as the ss links
- [x] fix example id highlighting to only highlight one at a time (in sublists, every sibling is highlighted)

**Comment by nschneid** [comment]
A minor polish thing: on a supersense page, mentions of that supersense are in bold. Wrapping them in `<span class="this-supersense">...</span>` would allow them to be styled with the same font as other supersenses. Maybe leave it to the `ss` macro to decide whether to display the supersense as a link or whether it's the one defined the current page?

**Comment by ablodge** [comment]
Can we make the title supersense black instead of green? (thinking of wikipedia-type style)
