### ISSUE TITLE
LaTeX: multicolumn examples

### ISSUE THREAD

**Issue by nschneid** [nert-gu/Xposition#93]
In the original document there are groups of examples organized in two columns under Theme, Gestalt, Possessor, Whole, SocialRel, and OrgRole to show the genitive alternation. Probably easiest just to simplify these to a single column. Currently the display of these examples is wonky.

**Comment by ablodge** [comment]
I think this is fixed in the most recent db.

**Comment by nschneid** [comment]
I'm still seeing problems in Theme, e.g. (014).

**Comment by nschneid** [comment]
(moved from another issue)

Regarding multicolumn example lists, note that `\sn` is equivalent to `\ex` but doesn't print an example number. For some of these lists, both columns have an `\sn` at the top which indicates the construal for the column.

**Comment by ablodge** [comment]
I converted them to tables. Try to think of a more sensible default heading than 1, 2

**Comment by nschneid** [comment]
Ooooh fancy!

There's a problem on Theme: the examples under the table shouldn't be indented.
