### ISSUE TITLE
Structural issues in LaTeX-converted supersense articles (lists/indentation, etc.)

### ISSUE THREAD

**Issue by nschneid** [nert-gu/Xposition#95]
E.g.:

- [x] Time: (005) shouldn't be an example, and examples following it should be indented
- [x] Circumstance: repeated list numbers
- [x] StartTime: "Prototypical prepositions..." is in a list item in the Markdown but not the original LaTeX. Was this intentional? It creates misalignment with the next paragraph ("Note that..."), which is not showing up in a list item.

These may have a common underlying cause, so I'll wait until they're fixed to look for more structural issues.

**Comment by ablodge** [comment]
I fixed the 2nd and 3rd by changing my strategy of making list items.
About the first:
"As meaning `when' (contrast ex:as-while under Circumstance):" is labeled with `\ex` in latex and contains preposition token. It's not obvious that there is any way to tell automatically that this isn't an example. Maybe rely on the colon at the end?

**Comment by nschneid** [comment]
Yeah maybe the colon at the end. Does prohibiting an example ending in a colon turn up any false negatives?

Another possibility is to recognize there's a sublist under it, so assume it's not an example. As far as I can recall the only exception is in the following, where there are multiple continuations of the example in a sublist (which can be perhaps recognized from `\dots`):

```latex
\ex It sounded \p{like}/\p{as\_if}
  \begin{xlist}
    \ex \dots he had drunk a gallon of helium. (\rf{Manner}{ComparisonRef}: analogy reading more likely)
    \ex \dots they weren't taking me seriously. (\rf{Theme}{ComparisonRef}: conclusion reading more likely)
  \end{xlist}
```

**Comment by nschneid** [comment]
Oh and sometimes multiple readings are presented without ellipses, but with square brackets:

```latex
\ex Do you want to talk \p{with} me? 
  \begin{xlist}
    \ex {}[\emph{The reading:} Should we have a conversation?] (\psst{Co-Agent})
    \ex {}[\emph{The reading:} Do you want to join me in talking to a third party?] 
      (\rf{Accompanier}{Co-Agent})
  \end{xlist}
  \ex I fought \p{with} them to reform the regulation.
  \begin{xlist}
    \ex {}[\emph{The reading:} I fought against them.] (\psst{Co-Agent})
    \ex {}[\emph{The reading:} I was on the same side as them.] (\rf{Accompanier}{Co-Agent})
  \end{xlist}
```

**Comment by nschneid** [comment]
- [ ] SocialRel (003)–(008) in the table should be SocialRel--Gestalt
- [ ] OrgRole (012)–(017): `\end{xlist}  \ex\begin{xlist}` shouldn't create a sublist even if a sublist is being ended
- [ ] Whole (025): Preposition in square brackets should be linked as an adposition, not a usage
- [ ] Quantity (020): Extra slash before "some"
- [ ] Characteristic (001–005) a.k.a. Identity (013–017): Usages should be Characteristic--Identity
- [ ] ComparisonRef (007), PartPortion (016): Rendering problem with subscripted annotation—and the usage links should match the subscripts.
- [ ] ComparisonRef (025–027): Extra escaping of underscore
- [ ] Identity (011–012): Too much indentation of examples

I looked through all the Configuration subtypes and these were the only issues I noticed, so we must be getting close!

**Comment by ablodge** [comment]
There are 2 lines with `\ex`, `\p` and ending in ':' neither of which is an example:
Originator: "Originator--Agent (passive-by or adnominal by):"
Time "As meaning ‘when’ (contrast <ref>ex:as-while</ref> under Circumstance):"

**Comment by ablodge** [comment]
(2) above is sort of a weird problem. In the latex, (010-011) and (012-016) are at the same depth in terms of list structure. What is `\ex\begin{xlist} ... \end{xlist}` typically used for in the guides?

**Comment by ablodge** [comment]
Okay! All of the above are fixed.

**Comment by nschneid** [comment]
I took a look at all the Circumstance subtypes:

- [ ] Interval (001–005) usages are problematic: this is due to problems in the LaTeX (I will fix)
- [ ] Direction (009) and Manner (022): rendering issue with subscripts
- [ ] Goal (015), Frequency (007), Manner (030–031): non-target subscript shouldn't determine usage
- [ ] Source (020): (SUPERSENSE: explanation)
- [ ] Purpose: ideally the 3 subclasses (after "The following subclasses...") should be indented as they are in the PDF guidelines (but not crucial if it's a pain)

**Comment by ablodge** [comment]
The above problems are fixed except (5). 
About (5) above - There is no way to do this, unfortunately. Even if we change it by hand, django markdown won't display non-bulleted paragraphs under a list item.

**Comment by ablodge** [comment]
- [ ] When an example is followed by a reading - a non-example containing 'reading' - should it have no usage?

**Comment by nschneid** [comment]
> About (5) above - There is no way to do this, unfortunately. Even if we change it by hand, django markdown won't display non-bulleted paragraphs under a list item.

I was able to get it to work like this: https://gist.github.com/nschneid/3ed11fa47f1d9af4c631c1fb367b0112

Is this easy to automate, or not worth it?

**Comment by ablodge** [comment]
> Is this easy to automate, or not worth it?

It's not easy to automate. It would be better to do this by hand.

**Comment by nschneid** [comment]
Looking great. I could only find 3 issues:

- [ ] Quantity: rendering problem after (019)
- [ ] Beneficiary: before (007), missing line breaks before numbered subsection headings
- [ ] The multiple readings under ComparisonRef (029) aren't formatted the same as the others

**Comment by ablodge** [comment]
The above are fixed.

**Comment by nschneid** [comment]
- [ ] I think we have a regression on Beneficiary: (018) and (019) have extra underlined spaces next to slashes
