### ISSUE TITLE
Macro for glossed examples

### ISSUE THREAD

**Issue by nschneid** [nert-gu/Xposition#98]
Called `gex`? It could take as arguments:

- a string with the tokenized sentence
- a string with the tokenized word-level glosses
- a string with the sentence gloss

Or the word-level info could have nested structure, e.g. `[gex "{L' the}{éléphant elephant} {est is} {[p fr/dans Locus] [p en/in Locus]} {la the} {voiture car}."]` This would remove the need for space-tokenization that might look confusing in some orthographies.

**Comment by nschneid** [comment]
Neither of the above solutions allow for glossing a multiword unit (or for the word-level gloss to be a multiword unit). How about the following spec for `gex`:

`gex` is an extension of the `ex` macro that allows for word- and sentence-level glossing. It contains the following arguments; the 2nd and 3rd must be double-quoted strings:

1. a key that uniquely identifies the example within the article
2. the source string, typically containing nested macros such as `p`, and optionally containing word-level glosses
3. (optional) a sentence-level gloss, which also may contain nested macros

The source string may indicate word-level glosses with `{SOURCE TARGET}` notation (if neither source nor target contains a space) and `{SOURCE||TARGET}` notation (if one or both of the source and target contains a space). (Spaces within a nested macro call are not counted.) E.g.:

`[gex 001 "{L' the}{éléphant elephant} est<br> {[p fr/dans Locus] [p en/in Locus]} {la voiture||the car}."]`

This approach would allow us to further support more than 2 word-level lines, such as `{SOURCE TRANSLITERATION GLOSS}` or `{SOURCE||TRANSLITERATION||GLOSS}`.

I assume the need for displaying curly braces in glossed examples is rare, and can be done with HTML-escaping: `&#123;` and `&#125;`

**Comment by ablodge** [comment]
> Spaces within a nested macro call are not counted.

This part is sort of hard to do with regex. It might be easier to to encourage `{[p fr/dans Locus]||[p en/in Locus]}`

**Comment by nschneid** [comment]
How are nested macro calls processed—outside in, or inside out?

**Comment by ablodge** [comment]
I think they are processed sequentially by macro name dependeing on how they appear in the list.

**Comment by ablodge** [comment]
ex is listed first, so it’s outside in.

**Comment by nschneid** [comment]
But ex could be moved last so it would be inside-out? Can it tell if part of its argument is the output of another macro?

**Comment by nschneid** [comment]
(`{[p fr/dans Locus]||[p en/in Locus]}` would be fine. I'm just trying to wrap my head around how the macro system works.)

**Comment by ablodge** [comment]
I recall there was a problem if we put them in a different order. If ex isn’t first the nested macros won’t render. 

I don’t think macros can detect nested macros, but it’d be easy to catch them with regex.

**Comment by ablodge** [comment]
How do I add interlinear.css?

**Comment by nschneid** [comment]
Just stick it in metadata.css.

**Comment by nschneid** [comment]
Oh, you mean you see that on the page? That means it's escaping the `<br/>` tags rather than interpreting them as HTML. If you're sure that the only uses of angle brackets, quotes, and ampersands are for HTML, then you can call `mark_safe()` on the produced string so Django doesn't automatically escape it. But you may want to call `escape()` on the textual arguments of the macro when assembling the string. An alternative to `escape()` + `mark_safe()` is `format_html(pattern, arg_to_escape1, arg_to_escape2, ...)`.

**Comment by ablodge** [comment]
Thanks. It also looks like the table is displayed sideways. Is some feater of interlinear.css supposed to flip it?

**Comment by ablodge** [comment]
`valign: top`?

**Comment by nschneid** [comment]
`valign` isn't actually valid CSS. But other stuff in the CSS is necessary for the layout to be correct.

**Comment by ablodge** [comment]
I did the following:
```
format_html(f'''<span id="{id}" class="example">
                    <div class="interlinear">
                    <p class="gloss">
                        {{}}
                    </p>
                    <p class="translation">{{}}</p>
                    </div>&nbsp;<a href="#{id}" class="exlabel">{id}</a></span>
                    ''', mark_safe(interlinear), sent_gloss)
```
It still displays `<br />` on the page.

**Comment by nschneid** [comment]
To `format_html()` you should only pass arguments that need escaping. If you replace `{{}}` with `{interlinear}` it should work.

**Comment by nschneid** [comment]
Pseudocode for `format_html()`:

```py
def format_html(pattern, *args):
    s = pattern
    for a in args:
        s = s.replace('{}', escape(a), 1)
    return mark_safe(s)
```

**Comment by ablodge** [comment]
Still no. Can you take a look at the code?

**Comment by nschneid** [comment]
Hmm, it looks OK to me! What is the value of `interlinear` when the function returns?

**Comment by ablodge** [comment]
Oh! If I add 'br' to  WIKI_MARKDOWN_HTML_WHITELIST, it works.

**Comment by nschneid** [comment]
Ahhhhh.

**Comment by ablodge** [comment]
The display is still sideways:

```
L'
the

éléphant
elephant

gris
gray est dans
in

la voiture
the car . 

The gray elephant is in the car.
 999 
```

**Comment by ablodge** [comment]
Okay. Got it.
![pic](https://user-images.githubusercontent.com/11709538/43370198-d343edd0-9348-11e8-801a-a0e7b6840b05.png)

**Comment by nschneid** [comment]
![image](https://www.raptonline.co.nz/user/images/24674.jpg?t=1602031317)
