### ISSUE TITLE
PP idioms

### ISSUE THREAD

**Issue by nschneid** [nert-gu/Xposition#99]
I don't see PP idioms in the database. Did we decide not to import them from STREUSLE? I think this might confuse people looking at the example sentences.

I'm talking about MWEs with lexcat `PP`. Syntactic PPs classified as discourse expressions (lexcat `DISC`) don't count.

**Comment by ablodge** [comment]
I'll add it. Right now we import laxcats `['P', 'PRON.POSS', 'POSS', 'PP']`. Is there anything missing?

**Comment by nschneid** [comment]
`INF.P`

**Comment by nschneid** [comment]
I guess the `Adposition` model doesn't provide a way to distinguish PP idioms from regular adpositions. Is the transitivity field confusing? (Syntactically a PP is transitive internally, but the PP as a whole is intransitive.) Maybe there should be a transitivity = PP option?

**Comment by ablodge** [comment]
I think the transitivity field makes more sense the way it is. The easiest thing would be to add a boolean field is_pp_idiom.

**Comment by nschneid** [comment]
Are you considering the PP idioms to be transitive or intransitive?

**Comment by ablodge** [comment]
A PP idiom like "in_no_time" is intransitive. That helps us distinguish them from multiword adpositions with an external argument like "with_the_exception_of".

**Comment by nschneid** [comment]
OK. I think it would be good to have a field that distinguishes them from intransitive particles.
